site_name: トランスルー｜翻訳支援サーバ
site_description: 翻訳支援サーバ「トランスル－」のドキュメントページです
site_author: nao
copyright: Copyright &copy; 2020 -  N,Mori/*nao*
theme:
  name: material
  language: ja
  locale: ja
  separator: '[\s\-\.]+'
  logo: images/logo.png
  favicon: images/favicon.png
  features:
    - content.tabs.link
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.section
    - navigation.footer
    #- toc.integrate
  font:
    text: BIZ UDPGothic
  palette:
    - media: "(prefers-color-scheme)"
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-auto
        name: ライトモードに切り替えます。
    - media: "(prefers-color-scheme: light)"
      primary: blue
      accent: blue
      scheme: default      
      toggle:
          #icon: material/toggle-switch-off-outline
          icon: material/brightness-7 
          name: ダークモードに切り替えます。
    - media: "(prefers-color-scheme: dark)"            
      primary: blue
      accent: blue
      scheme: slate
      toggle:
          #icon: material/toggle-switch
          icon: material/brightness-4 
          name: オートモードに切り替えます。
extra:
  search:
    language: 'ja'
  analytics:
    provider: google
    property: G-8VEJJC6B3D
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/yncneo
  generator: true
markdown_extensions:
  - abbr
  - tables
  - attr_list
  - md_in_html
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - fontawesome_markdown
  - codehilite
  - pymdownx.emoji
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences    
  - pymdownx.highlight:
      anchor_linenums: true
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true      
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra_css:
    - "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"
    - css/extra.css
plugins:
  - git-revision-date-localized
  - search
  - glightbox
  - meta-descriptions:
      export_csv: false
      quiet: false
      enable_checks: false
      min_length: 50
      max_length: 160
nav:
    - トランスル―▼:
      - TOP: 'index.md'

